server:
  port: "8000"

mysql:
  dsn: "user:password@tcp(localhost:3306)/water_reminder?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secret: "your_jwt_secret_key"
  expire: 24 # hours